version: 2.1
jobs:
  test:
    docker:
      - image: circleci/php:7.4-node-browsers-legacy
        environment:
          APP_ENV: testing
          APP_KEY: base64:pzXA2hCv/Uqn416ctav9agYqahmLvrxpTgI4DlqOh0U=
          DB_CONNECTION: mysql
          DB_DATABASE: sandbox_test
          DB_USERNAME: root
          DB_PASSWORD: secret
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: sandbox_test

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install PHP extensions
          command: sudo docker-php-ext-install pdo_mysql

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: php artisan migrate
      - run: php artisan db:seed
      - run:
          name: Run tests
          command: phpdbg -qrr vendor/bin/phpunit --coverage-html build/coverage-report
      - store_artifacts:
          path:  build/coverage-report
